#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

## Launch always on programs
exec-once = nm-applet
exec-once = waybar
exec-once = discord

## Load Plugins
exec-once = hyprpm reload -n # split-monitor-workspaces
exec-once = hypridle
exec-once = awww-daemon
exec-once = swaync
