################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto
monitor=DP-3, 2560x1440@144, 0x0, 1               # Main 
monitor=HDMI-A-2, 1920x1200@60, 640x-1200, 1        # Top 
monitor=DP-4, 1920x1200@60, 2560x-480, 1, transform, 1  # Right 
monitor=DP-2, 1920x1200@60, -1920x0, 1                # Left 
